#!/bin/bash -e
ml singularity
APP=$1
if [ -z $DEBVERSION ]
then
	printf 'Error: $DEBVERSION is not set and exported\n'
	exit 1
fi

printf "==== $APP ====\n"

MODROOT=/apps/unit/BioinfoUgrp/DebianMed/$DEBVERSION
DEBMEDIMAGE=$MODROOT/DebianMed_$DEBVERSION.sif
APPDIR=$MODROOT/modules/$APP
VER=$(singularity exec $DEBMEDIMAGE dpkg-query -W -f='${Version}' $APP)
mkdir -p $APPDIR/$VER
cd $APPDIR/$VER

printf "   creating module in $APPDIR/$VER\n"

mkdir -p bin
for prog in $($DEBMEDIMAGE dpkg -L $APP | grep /bin/ | xargs basename -a)
do
cat <<__END__ > bin/$prog
#!/bin/sh
LC_ALL=C singularity exec $DEBMEDIMAGE $prog "\$@" 
__END__
chmod 775 bin/$prog
done
mkdir -p $MODROOT/modulefiles/$APP
cd $MODROOT/modulefiles/$APP

printf "   creating modulefile $VER in $MODROOT/modulefiles/$APP\n"

cat <<__END__ > $VER.lua
-- Default settings
local modroot    = "$MODROOT"
local appname    = myModuleName()
local appversion = myModuleVersion()
local apphome    = pathJoin(modroot, "modules", "$APP", appversion)

-- Package information
whatis("Name: "..appname)
whatis("Version: "..appversion)
whatis("URL: ".."https://github.com/oist/BioinfoUgrp")
whatis("Category: ".." bioinformatics")
whatis("Keywords: ".." Bioinformatics, Debian")
whatis("Description: ".." Module automatically generated by the Bioinfo user group.")

help([[This module runs from Singularity image of Debian Med.
Please contact the Bioinfo user group for details.]])

-- Package settings
depends_on("singularity")
prepend_path("PATH", apphome.."/bin")
__END__
